<?php
/**
 * @file
 * The custom site module for allravereviews.com
 *
 * Handles custom, miscellaneous functionality specific to allravereviews.com
 */

/**
 * Form functions
 */
$dir = dirname(__FILE__) . '/includes/forms/*.form.inc';

foreach (glob($dir) as $file) {
  include_once($file);
}

/**
 * Database call functions
 */
$file = dirname(__FILE__) . '/includes/arr_site_db_calls.inc';
include_once($file);

/**
 * Implementation of hook_init
 */
function arr_site_init() {
  global $_arr_site;
  
  $mod_path = drupal_get_path('module', 'arr_site');
  $vendor_type = variable_get('arr_site_vendor_node_type', '');
  $vid = variable_get('arr_site_vendor_vocabulary', 0);
  
  // Dropdown menu JS settings
  $settings = array(
    'menuMultiLevel' => array(
      'menus' => array(
        '.primary-navigation .content > .menu',
      ),
    ),
  );
  
  drupal_add_js($settings, 'setting');
  
  $_arr_site = array(
    'mod_path' => $mod_path,
    'vendor_type' => $vendor_type,
    'vendors_vocab' => $vid,
    'is_vendor_page' => FALSE,
    'breadcrumb_end' => '',
    'is_category_page' => FALSE,
  );
  
  if (strpos($_GET['q'], 'admin/structure/arr-manage-tech-specs/specs/') !== FALSE) {
    drupal_add_css($mod_path.'/styles/css/admin-styles.css', array('every_page' => FALSE, 'preprocess' => FALSE));
    drupal_add_js($mod_path.'/js/admin.js', array('every_page' => FALSE, 'preprocess' => FALSE));
  } elseif (preg_match('/^node\/([0-9]+)$/', $_GET['q'], $matches)) {
    $nid = $matches[1];
    
    if (is_numeric($nid)) {
      $node = node_load($nid);
      $node_type = !empty($node->type) ? $node->type : '';
      
      if ($node_type == $vendor_type) {
        $_arr_site['is_vendor_page'] = TRUE;
        
        $_arr_site['breadcrumb_end'] = $node->title;
      }
    }
  }
  
  $tid = arr_site_is_category_page($vid);
  $_arr_site['is_category_page'] = !empty($tid);
  
  if ($_arr_site['is_category_page']) {
    $_arr_site['arr_site_cat_specs'] = arr_site_fetch_tech_specs_by_tid($tid);
    $_arr_site['arr_site_node_specs'] = arr_site_fetch_node_spec_data_by_tid($tid);
  }
}

/**
 * Implementation of hook_menu
 */
function arr_site_menu() {
  $items['admin/structure/arr-manage-tech-specs'] = array(
    'title' => 'Administer Tech Specs',
    'description' => 'From this page you can add, edit, and delete Tech Specs.',
    'page callback' => 'arr_site_page_manage_tech_specs',
    'type' => MENU_NORMAL_ITEM,
    'access callback' => 'arr_site_access_tech_specs',
  );
  
  $items['admin/structure/arr-manage-tech-specs/settings'] = array(
    'title' => 'ARR Tech Spec Settings',
    'description' => 'From this page you can configure settings for the Tech Specs.',
    'page callback' => 'arr_site_page_manage_tech_specs',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'access callback' => 'arr_site_access_tech_specs',
  );
  
  $items['admin/structure/arr-manage-tech-specs/categories'] = array(
    'title' => 'Categories',
    'description' => 'From this page you can add, edit, and delete Tech Spec Categories.',
    'page callback' => 'arr_site_page_manage_tech_specs',
    'page arguments' => array(3),
    'type' => MENU_LOCAL_TASK,
    'access callback' => 'arr_site_access_tech_specs',
  );
  
  $items['admin/structure/arr-manage-tech-specs/categories/add-category'] = array(
    'title' => 'Add Category',
    'description' => 'Add a new technical specification category.',
    'page callback' => 'arr_site_page_manage_tech_specs',
    'page arguments' => array(4),
    'type' => MENU_LOCAL_ACTION,
    'access callback' => 'arr_site_access_tech_specs',
  );
  
  $items['admin/structure/arr-manage-tech-specs/%/edit-category/%'] = array(
    'title' => 'Edit Tech Spec Category',
    'description' => 'Edit a technical specification category.',
    'page callback' => 'arr_site_page_manage_tech_specs',
    'page arguments' => array(4, 3, 5),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => 'arr_site_access_tech_specs',
  );
  
  $items['admin/structure/arr-manage-tech-specs/%/clone-category'] = array(
    'title' => 'Clone Tech Spec Category',
    'description' => 'Clone a technical specification category.',
    'page callback' => 'arr_site_page_manage_tech_specs',
    'page arguments' => array(4, 3),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => 'arr_site_access_tech_specs',
  );
  
  $items['admin/structure/arr-manage-tech-specs/%/map-category'] = array(
    'title' => 'Map Category to Terms',
    'description' => 'Add or remove mapping between this category and vendor vocabulary terms',
    'page callback' => 'arr_site_page_manage_tech_specs',
    'page arguments' => array(4, 3),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => 'arr_site_access_tech_specs',
  );
  
  $items['admin/structure/arr-manage-tech-specs/%/delete-category'] = array(
    'title' => 'Delete Tech Spec Category',
    'description' => 'Delete a technical specification category from all vendor types.',
    'page callback' => 'arr_site_page_manage_tech_specs',
    'page arguments' => array(4, 3),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => 'arr_site_access_tech_specs',
  );
  
  $items['admin/structure/arr-manage-tech-specs/%/unmap-category/%'] = array(
    'title' => 'Unmap Tech Spec Category',
    'description' => 'Delete a technical specification category from this vendor type.',
    'page callback' => 'arr_site_page_manage_tech_specs',
    'page arguments' => array(4, 3, 5),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => 'arr_site_access_tech_specs',
  );
  
  $items['admin/structure/arr-manage-tech-specs/specs'] = array(
    'title' => 'Tech Specs',
    'description' => 'From this page you can add, edit, and delete Tech Specs.',
    'page callback' => 'arr_site_page_manage_tech_specs',
    'page arguments' => array(3),
    'type' => MENU_LOCAL_TASK,
    'access callback' => 'arr_site_access_tech_specs',
  );
  
  $items['admin/structure/arr-manage-tech-specs/specs/add'] = array(
    'title' => 'Add Tech Spec',
    'description' => 'Add a new technical specification.',
    'page callback' => 'arr_site_page_manage_tech_specs',
    'page arguments' => array(4),
    'type' => MENU_LOCAL_ACTION,
    'access callback' => 'arr_site_access_tech_specs',
  );
  
  $items['admin/structure/arr-manage-tech-specs/%/edit/%'] = array(
    'title' => 'Edit Tech Spec',
    'description' => 'Edit a technical specification.',
    'page callback' => 'arr_site_page_manage_tech_specs',
    'page arguments' => array(4, 3, 5),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => 'arr_site_access_tech_specs',
  );
  
  $items['admin/structure/arr-manage-tech-specs/%/delete'] = array(
    'title' => 'Delete Tech Spec',
    'description' => 'Delete a technical specification from all vendor types.',
    'page callback' => 'arr_site_page_manage_tech_specs',
    'page arguments' => array(4, 3),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => 'arr_site_access_tech_specs',
  );
  
  $items['admin/structure/arr-manage-tech-specs/%/unmap/%'] = array(
    'title' => 'Unmap Tech Spec',
    'description' => 'Delete a technical specification from this vendor type.',
    'page callback' => 'arr_site_page_manage_tech_specs',
    'page arguments' => array(4, 3, 5),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => 'arr_site_access_tech_specs',
  );
  
  $items['node/%/arr-tech-specs'] = array(
    'title' => 'Tech Specs',
    'page callback' => 'arr_site_page_tech_specs',
    'page arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    'access callback' => 'arr_site_access_tech_specs',
  );
  
  return $items;
}

/**
 * Implementation of hook_admin_paths
 */
function arr_site_admin_paths() {
  $paths = array(
    'node/*/arr-tech-specs' => TRUE,
  );
  
  return $paths;
}

/**
 * Implementation of hook_views_api()
 */
function arr_site_views_api() {
  global $_arr_site;
  
  $mod_path = !empty($_arr_site['mod_path']) ? $_arr_site['mod_path'] : drupal_get_path('module', 'arr_site');
  
  return array(
    'api' => 3,
    'path' => $mod_path . '/includes/views', 
    'template path' => $mod_path . '/themes',
  );
}

/**
 * Page callback for the tech specs admin pages
 */
function arr_site_page_manage_tech_specs($page = NULL, $id = 0, $vendor_tid = 0) {
  $output = array();
  
  $forms = array(
    'delete' => 'arr_site_delete_tech_spec',
    'delete-category' => 'arr_site_delete_tech_spec_category',
  );
  
  $forms['unmap'] = $forms['delete'];
  $forms['unmap-category'] = $forms['delete-category'];
  $forms['clone-category'] = $forms['map-category'] = 'arr_site_clone_tech_spec_category';
  $forms['add'] = $forms['edit'] = 'arr_site_edit_tech_spec';
  $forms['add-category'] = $forms['edit-category'] = 'arr_site_edit_tech_spec_category';
  
  if (!isset($page)) {
    $output = drupal_get_form('arr_site_edit_tech_spec_settings');
  } else {
    if (!empty($forms[$page])) {
      if ($page == 'map-category') {
        $output = drupal_get_form($forms[$page], $id, 'map');
      }
      elseif ($page == 'clone-category') {
        $output = drupal_get_form($forms[$page], $id, 'clone');
      } else {
        $output = drupal_get_form($forms[$page], $id, $vendor_tid);
      }
    } elseif ($page == 'categories' || $page == 'specs') {
      $output = drupal_get_form('arr_site_tech_spec_lists', $page);
    }
  }
  
  return $output;
}

/**
 * Page callback for the tech specs page
 */
function arr_site_page_tech_specs($nid = 0) {
  if (empty($nid)) drupal_goto('admin/content');
  
  $output = drupal_get_form('arr_site_edit_node_tech_specs', $nid);
  
  return $output;
}

/**
 * Access callback for the tech specs page
 */
function arr_site_access_tech_specs() {
  global $user, $_arr_site;
  
  $type = !empty($_arr_site['vendor_type']) ? $_arr_site['vendor_type'] : '';
  
  $output = TRUE;
  
  if (in_array('administrator', array_values($user->roles))) {
    $q = $_GET['q'];
    
    if (preg_match('/node\/([0-9]+)\/edit/', $q, $matches)) {
      $nid = $matches[1];
      $node = node_load($nid);
      
      if ($node->type != $type) {
        $output = FALSE;
      }
    }
  }
  
  return $output;
}

/**
 * Builds table markup for category and tech spec list pages
 */
function _arr_site_tech_spec_list_table($cols, $rows, $category = FALSE, $vendor_tid = 0) {
  $col_count = count($cols);
  
  $output =
    '<table>'."\n"."\t".
      '<thead>'."\n"."\t"."\t".
        '<tr>'."\n"."\t"."\t"."\t";
  
  foreach ($cols as $label) {
    $output .= '<th>'.t("@label", array('@label' => $label)).'</th>'."\n"."\t"."\t"."\t";
  }
  
  $output .=
          '<th colspan="3">'.t('Operations').'</th>'."\n"."\t"."\t".
        '</tr>'."\n"."\t".
      '</thead>'."\n"."\t".
      '<tbody>'."\n"."\t";
  
  foreach ($rows as $id => $row) {
    $output .=
        "\t".
        '<tr>'."\n"."\t"."\t"."\t";
    
    foreach ($row as $key => $td) {
      $output .=
          '<td>'.t("@td", array('@td' => $td)).'</td>'."\n"."\t"."\t"."\t";
    }
    
    $l_suff = ($category) ? '-category' : '';
    $el = $dl = $um = 'admin/structure/arr-manage-tech-specs/'.$id.'/';
    
    $el .= 'edit'.$l_suff.'/'.$vendor_tid;;
    $dl .= 'delete'.$l_suff;
    $um .= 'unmap'.$l_suff.'/'.$vendor_tid;
    
    $el = l('edit', $el);
    $dl = l('delete', $dl);
    $um = l('unmap', $um);
    
    $output .=
          '<td>'.$el.'</td>'."\n"."\t"."\t"."\t".
          '<td>'.$dl.'</td>'."\n"."\t"."\t"."\t".
          '<td>'.$um.'</td>'."\n"."\t"."\t"."\t".
        '</tr>'."\n"."\t";
  }
  
  $output .=
      '</tbody>'."\n".
    '</table>';
      
  
  return $output;
}


/*********************
BLOCKS
*********************/
/**
 * Implements hook_block_info()
 */
function arr_site_block_info() {
  $blocks = array();
  
  $blocks['related_categories'] = array(
    'info' => t('Related Categories Block'),
  );
  
  return $blocks;
}

/**
 * Implements hook_block_configure()
 */
function arr_site_block_configure($delta = '') {
  $form = array();
  
  switch ($delta) {
    case 'related_categories': {
      break;
    }
  }
  
  return $form;
}

/**
 * Implements hook_block_save()
 */
function arr_site_block_save($delta = '', $edit = array()) {
}

/**
 * Implements hook_block_view()
 */
function arr_site_block_view($delta = '') {
  $block = array(
    'subject' => NULL,
    'content' => array(),
  );
  
  switch ($delta) {
    case 'related_categories': {
      $block['subject'] = 'Related Categories';
      $block['content'] = 'testing';
      break;
    }
  }
  
  return $block;
}

/**
 * Implementation of template_preprocess_page()
 */
function arr_site_preprocess_page(&$vars) {
  global $_arr_site;
  
  $is_category_page = !empty($_arr_site['is_category_page']);
}

/**
 * Implementation of template_preprocess_node()
 */
function arr_site_preprocess_node(&$vars) {
  global $_arr_site;
  
  if (!isset($_arr_site['node_count'])) {
    $_arr_site['node_count'] = 0;
  }
  
  $vendor_type = !empty($_arr_site['vendor_type']) ? $_arr_site['vendor_type'] : '';
  $node_type = !empty($vars['node']->type) ? $vars['node']->type : '';
  $is_category_page = !empty($_arr_site['is_category_page']);
  
  if (empty($vendor_type) || ((empty($node_type) || $vendor_type != $node_type) && !$is_category_page)) return;
  
  if ($is_category_page && $_arr_site['node_count'] == 0) {
    $vars['classes_array'][] = 'first-vendor';
    $_arr_site['node_count']++;
  }
  
  $tech_specs = array(
    '#tree' => TRUE,
    '#prefix' => '<div id="node-tech-specs-collapsibles">',
    '#suffix' => '</div>',
  );
  
  $vars['node_spec_data'] = $node_spec_data = arr_site_fetch_tech_specs_for_node($vars['node']);
  
  extract($node_spec_data);
  if (empty($groups)) return;
  
  foreach ($groups as $group) {
    if (empty($group['rows'])) return;
    
    foreach ($group['rows'] as $cat_id => $data) {
      if (!empty($data['rows'])) {
        $temp_spec = array();
        $cat_name = $data['cat'];
        
        $temp_spec = array(
          '#tree' => TRUE,
          '#prefix' => '<div class="node-specs collapsible-container">'."\n",
          '#suffix' => '</div>'."\n",
        );
        
        $temp_spec['top'] = array(
          '#markup' => '<a href="#collapse-cat-'.$cat_id.'">'.t('@cat_name', array('@cat_name' => $cat_name)).'</a>'."\n",
          '#prefix' => '<div class="node-spec-cat-title">',
          '#suffix' => '</div>',
        );
        
        $temp_spec['bottom'] = array(
          '#tree' => TRUE,
          '#prefix' => '<div id="collapse-cat-'.$cat_id.'" class="collapsible tech-spechs">'."\n",
          '#suffix' => '</div>'."\n",
        );
        
        $specs_count = $specs_total = 0;
        
        foreach ($data['rows'] as $ckey => $d) {
          if (isset($specs[$ckey])) {
            $specs_total++;
          }
        }
        
        if (!empty($specs_total)) {
          $tech_specs[$cat_id] = $temp_spec;
          
          foreach ($data['rows'] as $ckey => $d) {
            if (isset($specs[$ckey])) {
              $row_class = (($specs_count % 2) == 0) ? 'even' : 'odd';
              
              if ($specs_count == ($specs_total -1)) $row_class .= ' last';
              
              $spec = $specs[$ckey];
              $has_spec = !empty($spec['has_spec']) ? TRUE : FALSE;
              $comment = $spec['spec_comment'];
              
              if (empty($comment) && $has_spec) {
                $spec_val = 'Yes';
              } elseif (!empty($comment)) {
                $spec_val = $comment;
              } else {
                $spec_val = 'N/A';
              }
              
              $tech_specs[$cat_id]['bottom'][$ckey] = array(
                '#markup' =>
                  '<div class="specs-left">'.t('@spec_name', array('@spec_name' => $d)).'</div>'.
                  '<div class="specs-right">'.t('@spec_val', array('@spec_val' => $spec_val)).'</div>',
                '#prefix' => '<div class="specs-row '.$row_class.'">',
                '#suffix' => '</div>',
              );
              
              $specs_count++;
            }
          }
        }
      }
    }
  }
  
  $vars['tech_specs'] = $tech_specs;
}

/**
 * Implementation of hook_webform_select_options_info().
 * See webform/webform_hooks.php for further information on this hook in the Webform API.
 */
function arr_site_webform_select_options_info() {
  $items = array();
  
  $items['arr_vendor_categories'] = array(
    'title' => t('Vendor Categories'),
    'options callback' => 'arr_webform_pre_build_list_vendor_categories',
  );
  
  $items['arr_vendors'] = array(
    'title' => t('Vendors'),
    'options callback' => 'arr_webform_pre_build_list_vendors',
  );
  
  return $items;
}

/**
 * Implements hook_field_formatter_info()
 */
function arr_site_field_formatter_info() {
  return array(
    'arr_site_home_slide_title' => array(
      'label' => t('Slide Title'),
      'field types' => array('text'),
      'description' => t('Renders the field as a title for a slide in the homepage slideshow.'),
    ),
    'arr_site_home_slide_content' => array(
      'label' => t('Slide Content'),
      'field types' => array('text', 'text_with_summary', 'text_long'),
      'description' => t('Renders the field for display as the main content of a slide in the homepage slideshow.'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function arr_site_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array(); // Initialize the var
  
  switch ($display['type']) {
    case 'arr_site_home_slide_title': {
      foreach ($items as $delta => $item) {
        $title = !empty($item['safe_value']) ? $item['safe_value'] : $item['value'];
        $element[$delta] = array(
          '#markup' => $title,
          '#prefix' => '<div class="left"><div class="inner"><h2>',
          '#suffix' => '</h2></div></div>',
        );
      }
      
      break;
    }
    
    case 'arr_site_home_slide_content': {
      foreach ($items as $delta => $item) {
        $content = !empty($item['safe_value']) ? $item['safe_value'] : $item['value'];
        $element[$delta] = array(
          '#markup' => $content,
          '#prefix' => '<div class="right">',
          '#suffix' => '</div>',
        );
      }
      break;
    }
  }
  
  return $element;
}

/**
 * Implements hook_cron()
 */
function arr_site_cron() {
  // Delete orphaned spec categories
  $sql =
    'SELECT `tid` ' .
    'FROM {taxonomy_term_data};';
  $result = db_query($sql);
  
  $active_tids = array();
  foreach ($result as $row) {
    $active_tids[] = $row->tid;
  }
  
  $sql =
    'SELECT `tid` ' .
    'FROM {arr_spec_cat_map} ' .
    'GROUP BY `tid` ' .
    'ORDER BY `tid`;';
  $result = db_query($sql);
  
  $deleted_tids = array();
  foreach ($result as $row) {
    if (!in_array($row->tid, $active_tids)) {
      $deleted_tids[] = $row->tid;
    }
  }
  
  foreach ($deleted_tids as $tid) {
    arr_site_delete_all_spec_data_for_tid($tid);
  }
}
